kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: devadmin
  namespace:  bidder-dev
subjects:
  - kind: User # May be "User", "Group" or "ServiceAccount"
    name: kube-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io